[package]
name = "fhc"
version = "0.10.0"
authors = ["Eduard Tolosa <edu4rdshl@protonmail.com>"]
edition = "2021"
description = "Fast HTTP Checker."
repository = "https://github.com/edu4rdshl/fhc"
license = "GPL-3.0-or-later"
keywords = ["http", "https", "http-checker"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "io-std", "io-util"] }
futures = "0.3.34"
clap = { version = "4.6.6", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["hickory-dns", "native-tls"] }
openssl = { version = "0.10.81", features = ["vendored"] }
rand = "0.10.2"
scraper = "0.27.0"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
